[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  |*.toml
  |*.txt
  |*.yml
  |*.sh
  |*.git
  |*.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
force-exclude = '''
/(
   /docs
   /docs/*
)\
'''

[tool.isort]
profile = "black"
reverse_relative = true
known_first_party = ["ibl_to_nwb"]
