name: IBL2NWB
channels:
  - conda-forge
  - defaults
dependencies:
 - python >=3.6
 - pyarrow >=1.0.0
 - pip:
   - ndx_ibl_metadata
   - git+https://github.com/catalystneuro/nwb-conversion-tools.git@fb9703f8e86072f04356883975e5dfffa773913e#egg=nwb-conversion-tools
   - ndx-spectrum==0.2.2
   - ibllib
   - lazy-ops
