"""Patches for tampered SpikeGLX .meta files found on the IBL server.

Some IBL sessions (NR_0029 from steinmetzlab, subject recorded in Aug-Sep 2023)
have .meta files that were rewritten after recording by an automated tool. The
rewritten files contain ``original_meta=False`` and have two problems that break
neo's SpikeGLX reader:

1. Missing ``~`` prefix on list-type fields.

   SpikeGLX meta files use a ``~`` prefix to mark fields whose values are
   parenthesized lists, e.g. ``~snsChanMap=(384,0,1)(AP0;0:0)...``. The
   rewriting tool stripped this prefix, leaving bare keys like ``snsChanMap=``.

   Neo's ``read_meta_file()`` only splits on ``)(`` when the key starts with
   ``~``. Without it, the entire value is stored as a plain string. When neo
   later iterates over ``meta["snsChanMap"]`` to extract channel names, it
   iterates over individual characters instead of parenthesized entries,
   producing thousands of single-character "names". The first ``nSavedChans``
   of these contain many duplicates, causing::

       ValueError: signal_channels do not have unique ids for stream 0

   Affected fields: ``snsChanMap``, ``imroTbl``, ``snsShankMap`` (both AP and
   LF metas).

2. LF meta ``fileName`` pointing to the AP binary.

   The LF .meta file was generated by copying the AP .meta and patching only
   four fields (``acqApLfSy``, ``fileSizeBytes``, ``imSampRate``, ``snsApLfSy``).
   The ``fileName`` field was left unchanged, so it still says ``.ap.bin``
   instead of ``.lf.bin``.

   Neo's ``extract_stream_info()`` uses ``meta["fileName"]`` to determine the
   stream type (``ap`` vs ``lf``). When both AP and LF metas claim to be AP
   streams, neo raises::

       KeyError: "key (0, 'imec0.ap') is already in the signals_info_dict"

3. Rewritten ``snsSaveChanSubset`` conflating neural and sync channels.

   The rewriting tool changed ``snsSaveChanSubset`` from the original
   non-contiguous range (e.g. ``0:47,96:143,384``) to a contiguous range
   (``0:96``). The original range explicitly separates 96 neural channels
   (in two ranges) from the sync channel (384). The rewritten ``0:96``
   makes probeinterface think there are 97 saved neural channels (0
   through 96 inclusive), because channel 96 appears contiguous with 0-95
   instead of being identified as the sync channel.

   Neo correctly excludes the sync channel (it uses ``snsApLfSy`` for
   that), so the recording extractor reports 96 channels. But
   probeinterface uses ``snsSaveChanSubset`` to slice the probe contacts
   and returns 97, which propagates into the electrode table. The
   mismatch causes a shape error during HDF5 write::

       TypeError: Can't broadcast (100, 96) -> (100, 97)

   The rewriting tool stored the original value in
   ``snsSaveChanSubset_orig``. This patch restores it.

4. Oversized ``snsChanMap`` and ``snsShankMap`` containing all 384 channels.

   SpikeGLX meta files normally list only the saved channels in
   ``~snsChanMap`` and ``~snsShankMap`` (one entry per saved channel,
   matching ``nSavedChans``). The rewriting tool dumped the full
   384-channel probe geometry into these fields instead of the saved
   subset. When neo reads channel names, it takes the first
   ``nSavedChans`` (97) entries from the 385-entry map. The 97th entry
   is ``AP96`` (a neural channel from the full map) instead of ``SY0``
   (the sync channel). Since neo identifies the sync channel by checking
   for ``"SY"`` in the channel name, it fails to separate it into its
   own stream. The main stream then has 97 channels but the probe only
   covers 96 contacts, causing::

       Exception: set_probe(inplace=True) must have all channel indices

   The fix trims ``~snsChanMap`` and ``~snsShankMap`` to only include
   entries for the channels listed in ``snsSaveChanSubset``.

The binary data itself is correct in all affected sessions.
"""

from __future__ import annotations

import logging
from pathlib import Path

_TILDE_PREFIX_FIELDS = {"snsChanMap", "imroTbl", "snsShankMap"}

# Fields whose entries must match snsSaveChanSubset (not the full 384-channel map)
_SAVED_SUBSET_FIELDS = {"~snsChanMap", "~snsShankMap"}


def fix_corrupted_spikeglx_meta_files(
    spikeglx_folder: Path,
    logger: logging.Logger,
) -> int:
    """Patch tampered SpikeGLX .meta files so neo can parse them.

    Scans all ``.meta`` files under *spikeglx_folder* and fixes:

    - Missing ``~`` prefix on list-type fields (``snsChanMap``, ``imroTbl``,
      ``snsShankMap``) in both AP and LF metas.
    - LF meta ``fileName`` pointing to the AP binary instead of the LF binary.
    - Rewritten ``snsSaveChanSubset`` restored from ``snsSaveChanSubset_orig``.
    - Oversized ``~snsChanMap`` / ``~snsShankMap`` trimmed to saved channels only.

    Idempotent: already-correct files are untouched.

    Returns the number of files patched.
    """
    patched = 0
    for meta_file in spikeglx_folder.rglob("*.meta"):
        text = meta_file.read_text()
        is_lf = meta_file.name.endswith(".lf.meta")

        # First pass: collect auxiliary fields needed for patching
        orig_chan_subset = None
        n_saved_chans = None
        saved_chan_subset = None
        for line in text.splitlines():
            key, _, value = line.partition("=")
            key = key.rstrip()
            value = value.rstrip()
            if key == "snsSaveChanSubset_orig":
                orig_chan_subset = value
            elif key == "nSavedChans":
                n_saved_chans = int(value)
            elif key == "snsSaveChanSubset":
                saved_chan_subset = value

        # Parse saved channel indices for trimming oversized snsChanMap/snsShankMap
        saved_indices = None
        subset_to_parse = orig_chan_subset or saved_chan_subset
        if subset_to_parse is not None and subset_to_parse != "all":
            saved_indices = _parse_chan_subset(subset_to_parse)

        new_lines = []
        file_changed = False
        for line in text.splitlines(keepends=True):
            key = line.split("=", 1)[0].rstrip()

            # Restore missing ~ prefix on list-type fields
            if key in _TILDE_PREFIX_FIELDS:
                new_key = f"~{key}"
                line = f"~{line}"
                file_changed = True
                key = new_key  # Update key for subsequent checks
                logger.warning(
                    "Patching missing ~ prefix in %s: %s -> %s",
                    meta_file.name,
                    key[1:],
                    new_key,
                )

            # Fix LF meta fileName pointing to AP binary
            if is_lf and key == "fileName" and ".ap.bin" in line:
                original_value = line.rstrip("\n").split("=", 1)[1]
                line = line.replace(".ap.bin", ".lf.bin")
                patched_value = line.rstrip("\n").split("=", 1)[1]
                file_changed = True
                logger.warning(
                    "Patching fileName in %s: %s -> %s",
                    meta_file.name,
                    original_value,
                    patched_value,
                )

            # Restore snsSaveChanSubset from snsSaveChanSubset_orig
            if key == "snsSaveChanSubset" and orig_chan_subset is not None:
                current_value = line.rstrip("\n").split("=", 1)[1]
                if current_value != orig_chan_subset:
                    line = f"snsSaveChanSubset={orig_chan_subset}\n"
                    file_changed = True
                    logger.warning(
                        "Patching snsSaveChanSubset in %s: %s -> %s",
                        meta_file.name,
                        current_value,
                        orig_chan_subset,
                    )

            # Trim oversized snsChanMap / snsShankMap to saved channels only
            if key in _SAVED_SUBSET_FIELDS and saved_indices is not None and n_saved_chans is not None:
                trimmed_line = _trim_parenthesized_field(line, key, saved_indices, n_saved_chans)
                if trimmed_line is not None:
                    original_count = line.count(")(")
                    new_count = trimmed_line.count(")(")
                    line = trimmed_line
                    file_changed = True
                    logger.warning(
                        "Trimming %s in %s: %d entries -> %d entries (matching nSavedChans=%d)",
                        key,
                        meta_file.name,
                        original_count + 1,
                        new_count + 1,
                        n_saved_chans,
                    )

            new_lines.append(line)

        if file_changed:
            meta_file.write_text("".join(new_lines))
            patched += 1

    return patched


def _parse_chan_subset(subset_str: str) -> list[int]:
    """Parse a ``snsSaveChanSubset`` value into a list of channel indices.

    Format: ``0:47,96:143,384`` where ``start:stop`` is inclusive on both ends.
    """
    indices = []
    for element in subset_str.split(","):
        if ":" in element:
            start, stop = element.split(":")
            indices.extend(range(int(start), int(stop) + 1))
        else:
            indices.append(int(element))
    return indices


def _trim_parenthesized_field(
    line: str,
    key: str,
    saved_indices: list[int],
    n_saved_chans: int,
) -> str | None:
    """Trim a parenthesized list field to only include saved channel entries.

    Returns the trimmed line, or ``None`` if no trimming is needed.

    SpikeGLX parenthesized fields like ``~snsChanMap`` and ``~snsShankMap``
    have the format::

        ~snsChanMap=(header)(entry_0)(entry_1)...(entry_N)

    where each entry corresponds to a readout channel index. When all 384
    channels are saved, there are 384 entries. When only a subset is saved
    (per ``snsSaveChanSubset``), only those entries should be present.
    """
    value = line.rstrip("\n").split("=", 1)[1]

    # Split into parenthesized entries: "(a)(b)(c)" -> ["a", "b", "c"]
    stripped = value.strip()
    if stripped.startswith("("):
        stripped = stripped[1:]
    if stripped.endswith(")"):
        stripped = stripped[:-1]
    entries = stripped.split(")(")

    header = entries[0]
    channel_entries = entries[1:]

    # Only trim if oversized (more entries than nSavedChans)
    if len(channel_entries) <= n_saved_chans:
        return None

    # Select only the entries at saved channel positions
    trimmed_entries = []
    for channel_index in saved_indices:
        if channel_index < len(channel_entries):
            trimmed_entries.append(channel_entries[channel_index])

    # Reconstruct the parenthesized format
    rebuilt = "(" + ")(".join([header] + trimmed_entries) + ")"
    return f"{key}={rebuilt}\n"
