name: Test Installation
on:
  workflow_call:

jobs:
  run:
    # Will read on PR dashboard as 'Deploy / TestInstallation / {python-version} on {os}'
    # Action dashboard identified by 'Dev tests'
    # Requirement settings identified as 'TestInstallation / Python {python-version} on {os}'
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - run: git fetch --prune --unshallow --tags

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: uv sync

      - name: Test import
        run: uv run python -c "import ibl_to_nwb"

      - name: Test data interface imports
        run: uv run python -c "import ibl_to_nwb.datainterfaces"

      - name: Test converters imports
        run: uv run python -c "import ibl_to_nwb.converters"
